### ISSUE TITLE
Clarification required over the link between an Authorisation Server's Issuer and it's Entity Identifier in a Federation

### ISSUE THREAD

**Issue by MichaelFraser1999** [openid/federation#101]
As it stands, there is no statement requiring an oauth_authorization_server's Entity Identifier to be the same as its issuer. Can we please confirm this is the intention? The example at https://openid.net/specs/openid-federation-1_0.html#section-5.1.3 suggests this to be intentional, where the entity identifier is `https://op.umu.se` and the issuer is listed as `https://op.umu.se/openid`. 

There are advantages to this being allowed as, by the current spec's text, multiple entities can exist for a single authorisation server and each issue different metadata profiles for this server. This has valid use cases for different offerings within an ecosystem (insurance provider vs banking provider as an example)

However, the problem it does introduce is discoverability when starting from a given authorisation server. If the issuer and the entity identifiers are aligned, any recipient of an ID token (as an example) would be able to take the issuer claim inside the token and infer the openid-configuration well-known's location from it. The same cannot be done for the openid-federation well-known if the two do not align. 

One possible solution would be to register an additional metadata item to be included in an authorisation servers's well-known response that would contain an array of all entity identifiers that alias this authorisation server so a consumer can work backwards from a given authorisation server

**Comment by vdzhuvinov** [comment]
Thank you, you made a crucial discovery, this was assumed, but is missing in the spec :)
