### ISSUE TITLE
Clearer descriptions federation endpoint specific metadata

### ISSUE THREAD

**Issue by selfissued** [openid/federation#104]
https://openid.net/specs/openid-federation-1_0-39.html#name-client-authentication-metad defines patterns for endpoint-specific metadata parameters.  Given that these can differ by endpoint, I understand why we have them.  The first question is whether we need separate *_auth_methods values, such as `federation_trust_mark_endpoint_auth_methods`.  I think we do, so that deployments can declare how to authenticate to their endpoints.

The second question is whether we need separate *_auth_signing_algs values, such as `federation_trust_mark_endpoint_auth_signing_algs`.  We currently do.

What made me ask this question is I proposed introducing `endpoint_authentication_signing_alg_values_supported` in PR #99 to declare the algorithms used for `private_key_jwt` request signing to federation endpoints.  Only afterwards did I realize that this overlaps with *_auth_signing_algs values.

We should decide this, and one of them should go away.

And I'd like to somehow make these metadata parameters more visible - probably in part by adding them to the list of metadata parameters at https://openid.net/specs/openid-federation-1_0-39.html#name-federation-entity, or at least putting some of them in the example there.

**Comment by vdzhuvinov** [comment]
I favour the simple solution - a single ` federation_entity` metadata parameter to indicate the supported auth methods and another for the associated JWS algs (if such are required).

I couldn't think of a compelling reason to have a separate auth metadata parameter for each endpoint. OIDC has managed with the simple approach -- for the token, PAR and CIBA endpoints.

**Comment by rohe** [comment]
I side with @vdzhuvinov

**Comment by selfissued** [comment]
Fixed by #99

**Comment by selfissued** [comment]
Fixed by #99
