### ISSUE TITLE
We don't say anything about require_signed_request_object

### ISSUE THREAD

**Issue by selfissued** [openid/federation#105]
We currently say nothing about the `[require_signed_request_object](https://www.rfc-editor.org/rfc/rfc9101.html#name-oauth-authorization-server-)` AS metadata parameter, even though we require signed request objects.

Should we require it to be present in the OP metadata?  Should we say that when using Federation, it's as if it's present?

FYI, there's also a corresponding client metadata parameter.

**Comment by SECtim** [comment]
> we require signed request objects

As far as I can see, this currently only applies to authentication requests with automatic registration. I.e., once registered (explicitly or automatically), clients are allowed to send "regular" authentication requests w/o request objects.

**Comment by selfissued** [comment]
This is also related to #99, particularly if we stop requiring Request objects with PAR.

**Comment by vdzhuvinov** [comment]
An OP accepting automatic registration at the authorisation endpoint MAY set the `require_signed_request_object`, but definitely MUST include `request_object_signing_alg_values_supported`.

An OP accepting automatic registration that requires PAR with `require_pushed_authorization_requests` will not set `require_signed_request_object`.

I hope this was of help to answer you question.

**Comment by selfissued** [comment]
On the 30-Oct-24 Federation editors' call, @vdzhuvinov suggested that we informatively say that that `require_signed_request_object` can be used, along with `require_pushed_authorization_requests` per #106
