### ISSUE TITLE
We don't say anything about require_pushed_authorization_requests

### ISSUE THREAD

**Issue by selfissued** [openid/federation#106]
We currently say nothing about the [require_pushed_authorization_requests](https://www.rfc-editor.org/rfc/rfc9126.html#name-authorization-server-metada) AS metadata parameter.  Should I explicitly say in PR #99, for instance, that it MAY be used?

FYI, there's also a corresponding client metadata parameter.

**Comment by vdzhuvinov** [comment]
Implementers and federations operators will benefit from a little guidance which OP/AS metadata parameters can be used in the context of Automatic Client Registration.
