### ISSUE TITLE
Trust Mark Delegation Revocation?

### ISSUE THREAD

**Issue by zachmann** [openid/federation#108]
Section 7.2.1 says about the `exp` claim of the delegation jwt:
> OPTIONAL. Number. Time when this delegation stops being valid. This is expressed as Seconds Since the Epoch, per [[RFC7519](https://openid.github.io/federation/main.html#RFC7519)]. If not present, it means that the delegation does not expire and is valid until revoked.

The very last part implies that the delegation jwt can be revoked. However, I cannot find any hints on a revocation mechanism for delegation jwts in the spec, also there is no status endpoint or other mechanism defined to verify the delegation apart from verifying the delegation jwt.

I would argue that the last part `and is valid until revoked` should be removed. It then would also be in line with the `exp` claim description of the trust mark jwt.

**Comment by selfissued** [comment]
I agree that we shouldn't talk about revocation when we have no mechanism to do it.

**Comment by vdzhuvinov** [comment]
The revocation of delegation JWTs is not specified in Federation / out of scope. 

Agree to remove the 

> and is valid until revoked
