### ISSUE TITLE
Inconsistent description of 'delegation' claim 

### ISSUE THREAD

**Issue by cicnavi** [openid/federation#116]
In [7.1](https://openid.net/specs/openid-federation-1_0.html#section-7.1) there is description of 'delegation' claim:

> delegation
OPTIONAL. The delegation claim defined in [Section 13.7](https://openid.net/specs/openid-federation-1_0.html#delegationClaim) is used in Trust Marks to delegate the right to issue Trust Marks with a particular identifier. Its value is a Trust Mark delegation JWT, as defined in [Section 7.2.1](https://openid.net/specs/openid-federation-1_0.html#delegation_jwt).

In [13.7](https://openid.net/specs/openid-federation-1_0.html#section-13.7) it states (wrongly) that it contains StringOrURI....:

> The delegation value is a case-sensitive string containing a StringOrURI value.

**Comment by selfissued** [comment]
The definition is correct in both cases.  For starters, a JWT, being a string of ASCII characters, is a valid StringOrURI value.  Here's the back story.

Section [13. ](https://openid.net/specs/openid-federation-1_0.html#section-13)[General-Purpose JWT Claims](https://openid.net/specs/openid-federation-1_0.html#name-general-purpose-jwt-claims) defines several claims intended for general use beyond just the Federation spec.  Their definitions are therefore as general as reasonable.  `delegation` is one of those claims.  Like many general-purpose JWT claims (such as `iss` and `sub`), it is defined as a StringOrURI.

The contents of the `delegation` claim when uses in OpenID Federation are refined in [7.2.1. ](https://openid.net/specs/openid-federation-1_0.html#section-7.2.1)[Trust Mark Delegation JWT](https://openid.net/specs/openid-federation-1_0.html#name-trust-mark-delegation-jwt) to be a Delegation JWT.  This is just like how OpenID Connect refines the contents of the `iss` and `sub` claims in [2. ID Token.](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) to be more specific than their general-purpose definitions in RFC 7519 in [4.1. Registered Claim Names](https://www.rfc-editor.org/rfc/rfc7519.html#section-4.1).

Does that make better sense now?

**Comment by cicnavi** [comment]
Definitely, thanks for clarification!
