### ISSUE TITLE
Resolver with multiple trust anchors

### ISSUE THREAD

**Issue by zachmann** [openid/federation#130]
The section on trust chain resolving makes it clear that it is feasible that an entity can have multiple trust anchors and wants to resolve a trust chain from a subject to any / multiple anchor(s) and then choose one.

At the same time the resolve endpoint does only allow one trust anchor. I think it would make sense to allow that the `anchor` parameter may be provided multiple times.

What do others think about this?

The resolver would need to choose which trust chain to use in the end; this is also with the current state the case, since there also can be multiple chains to a single trust anchor. However, the client might have preferences which trust anchor should be used, preferably. If this would be added, we might want to make a note about this. I see different options:

1. It's entirely up to the trust anchor which chain to choose and the trust anchor does not matter
2. The trust anchor should prefer the trust anchors in the order provided and only decide based on its own rules if there are multiple chains for a single trust anchor. (This would be equivalent to having the client making separate requests for all trust anchors, stopping at the first successful one)
3. The trust anchor decides based on its own rules which trust chain to use and only when having multiple equally valid options it considers the trust anchor.

I think option 3 is too vague and does not make too much sense. Option 2 could make sense.

**Comment by vdzhuvinov** [comment]
Does this proposal entail a change in the resolve response, to include the chosen Trust Anchor?

**Comment by zachmann** [comment]
It probably should. If the trust chain is included in the response it's not strictly necessary since it becomes clear from the chain. Still I think it is easier for clients to have a dedicated claim for it, if they want to check which trust anchor was chosen.

So, yes I would say a required parameter for the chosen trust anchor should be included in the response.

**Comment by peppelinux** [comment]
Multiple urlparams with the same name are possible

I suggest to return the response using the First matching trust anchor

**Comment by selfissued** [comment]
Do people agree with allowing multiple trust anchors to be specified in the request?

**Comment by peppelinux** [comment]
I agreed

Below some further clarifications

The response will not change, using more than a single trust anchors in the parameters It would mean to give at least One known  trust anchor to the resolver and let It decide which one to use in the response

In this case the trust chain parameters should be requires in the response or at least the trust_anchor used
