### ISSUE TITLE
Possible non-viable outcome for OID DC Registration metadata check in case of Automatic Registration

### ISSUE THREAD

**Issue by cicnavi** [openid/federation#133]
In OID Federation Automatic Registration, in [12.1.1.1.2. ](https://openid.net/specs/openid-federation-1_0.html#section-12.1.1.1.2)[Processing the Authentication Request](https://openid.net/specs/openid-federation-1_0.html#name-processing-the-authenticati), it says:

> The OP SHOULD furthermore verify that the resolved metadata of the RP complies with the client metadata specification [OpenID Connect Dynamic Client Registration 1.0](https://openid.net/specs/openid-federation-1_0.html#OpenID.Registration) [[OpenID.Registration](https://openid.net/specs/openid-federation-1_0.html#OpenID.Registration)].

OID DC Registration states about the following metadata param: 

> token_endpoint_auth_method
OPTIONAL. Requested Client Authentication method for the Token Endpoint. The options are client_secret_post, client_secret_basic, client_secret_jwt, private_key_jwt, and none, as described in Section 9 of [OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-registration-1_0.html#OpenID.Core) [OpenID.Core]. Other authentication methods MAY be defined by extensions. If omitted, the default is client_secret_basic -- the HTTP Basic Authentication Scheme specified in Section 2.3.1 of [OAuth 2.0](https://openid.net/specs/openid-connect-registration-1_0.html#RFC6749) [RFC6749].

If client has no `token_endpoint_auth_method` metadata defined (it is optional), and if there are no metadata policies defined which would set this metadata value during OID Federation Automatic Registration, according to OID DC Registration we would have to default to `client_secret_basic`, which is not viable since clients won't have client secret.

OID Federation should define default in this case, or add a note in the requirement for "...should verify that metadata complies with OID DC Registration...".

**Comment by vdzhuvinov** [comment]
I hold the position that the architect of the particular federation should deal with situations like this, by setting an appropriate `default` metadata parameter policy in the TA. Or require a specific value, like `private_key_jwt` or `self_signed_tls_client_auth`.

Last week we had a discussion where I proposed disallowing the `request_uri` entirely in auto registration . John Bradley convinced me it would be wiser to keep OIDC as it is as much as possible. OIDC has received a number of profiles already. I would find easier to have my standard mental picture of what OIDC is, and use the great tool that we have at our disposal - the policy language - to define defaults where necessary.

I'm okay to say, explicitly, in https://openid.net/specs/openid-federation-1_0.html#section-12.1.1.1.2 , that the OP must ensure the RP metadata conforms to its own OP metadata.

**Comment by cicnavi** [comment]
Hm, but the OP may express support for `client_secret_basic` in its metadata... 

I'm totally fine with the position of this being the federation architect responsibility, but I wanted to have a place I can point to if this particular situation ever comes up, even if that place is this issue.
