### ISSUE TITLE
Resolve Response and subject's federation jwks

### ISSUE THREAD

**Issue by zachmann** [openid/federation#137]
I start with a concrete use case:

- An entity wants to verify a trust mark
- It needs to build a trust chain to the trust mark issuer and relies on a resolver to do so
- It needs to verify the signature of the trust mark

Normally, it would obtain the jwks of the trust mark issuer from the tmi's entity configuration as part of the trust chain. However, we used a resolver, the resolve response does not contain the entity configuration or the subject's jwks.

There are different ways how this could be solved:
1. The `jwks` is included in the `metadata` under `federation_entity` in the resolve response
1. The `jwks` is in the entity configuration of the TMI, which is included in the `trust_chain` in the resolve response
1. The `jwks` is in the entity configuration of the TMI which can be simply queried.

I see different challenges with all of these approaches:
1. `jwks` in the `federation_entity` metadata is not required; the claim is not defined specifically for the `federation_entity` entity type, but is a common claim that can be used with all entity types, where section 5.2.1 states "Note that these keys are distinct from the Federation Entity Keys used to sign Entity Statements." which is obviously true for all entity types except `federation_entity`. It's unclear to me if for `federation_entity` the `jwks` there MAY/SHOULD/MUST be equivalent to the federation entity keys from the entity configuration. So it's not clear if this claim from the metadata can be used (even if it is set) to obtain the TMI's federation entity keys.
2. The `trust_chain` parameter is optional and might not be present. Furthermore it's add complexity for the client to parse the jwt to only obtain the federation entity keys.
3. This is always possible, but requires an additional request and again jwt parsing. Also it's unclear to me if the payload can be trusted (with regards to the jwks claim only) because the resolver was able to successfully build a trust chain or if the entity configuration would need to be properly verified, in which case the resolve request was superfluous.

The easiest solution would be to include the federation entity keys in the resolve response.

What do other's think about this?

**Comment by selfissued** [comment]
PR #141 clarifies that `jwks` in the `federation_entity` metadata is prohibited.  Federation Entity Keys are always in the `jwks` claim of the Entity Statement.

Does this help with the scenario you're envisioning, @zachmann ?

**Comment by zachmann** [comment]
Thanks for the PR; it certainly clarifies things and roles out option 1 in this issue.

I still think it would be nice to have the subject's jwks information in the resolve response. But I guess cases where this would be useful are indeed edge cases; the client still always can obtain the jwks itself. So I guess it's fine to close this.
