### ISSUE TITLE
PAR with the optional trust_chain parameter?

### ISSUE THREAD

**Issue by vdzhuvinov** [openid/federation#139]
The current spec leaves the read with the impression that the optional `trust_chain` parameter is intended only for use in request objects and not PAR.

https://openid.net/specs/openid-federation-1_0.html#section-12.1.1.1.1-1

> When the trust_chain request parameter is used in the Authorization Request Object, the Relying Party informs the OP of the sequence of Entity Statements that proves the trust relationship between it and the selected Trust Anchor.

Here is its registration, where we clearly have it as an authorisation request parameter:

https://openid.net/specs/openid-federation-1_0.html#section-17.5.1

**Comment by selfissued** [comment]
We've since updated that text in the editor's draft at https://openid.github.io/federation/main.html#section-12.1.1.1.1 to say:
> When the trust_chain request parameter is used in the authentication request, the Relying Party informs the OP of the sequence of Entity Statements that proves the trust relationship between it and the selected Trust Anchor.

Notice that we no longer say that the request is in a Request Object.  Does this address the issue in your mind, @vdzhuvinov ?

**Comment by vdzhuvinov** [comment]
> Notice that we no longer say that the request is in a Request Object. Does this address the issue in your mind, @vdzhuvinov ?

It has, thanks!

PR #142 will now also describe the request object in a neutral way that applies to both regular authentication requests and PAR.
