### ISSUE TITLE
[Resolve] trust_marks in the response

### ISSUE THREAD

**Issue by peppelinux** [openid/federation#18]
in https://openid.net/specs/openid-federation-1_0.html#section-8.3.2

In the resolver endpoint response, the trust_marks array must include the valid ones enabled by the trust anchor used in the request

**Comment by rohe** [comment]
Slightly rewritten.

Only valid trust marks that have been issued by trust mark issuers trusted by the trust anchor to issue such trust marks MUST appear in the resolver response.

**Comment by selfissued** [comment]
@peppelinux can you please create a PR incorporating @rohe's proposed wording?
