### ISSUE TITLE
Some examples for "add" metadata policy operator have wrong operator value type

### ISSUE THREAD

**Issue by cicnavi** [openid/federation#33]
In definition of 'add' policy operator [6.1.3.1.2. add](https://openid.net/specs/openid-federation-1_0.html#section-6.1.3.1.2), possible operator values are arrays only:

![image](https://github.com/user-attachments/assets/71a6de03-6109-47cd-9f8b-6f7a2290bf9f)

However, there are some examples of this policy operator which uses string for value:

![image](https://github.com/user-attachments/assets/b06af74b-6aa8-4cca-870f-8a13333c1ee4)

By searching for pattern 'add": "', I could find 5 of those cases (there are also examples which use arrays).

**Comment by selfissued** [comment]
We discussed this on the 14-Aug-24 Federation editors' call.  We agree that this needs to be corrected.  @rohe will create a PR.

**Comment by vdzhuvinov** [comment]
Good catch, thanks for filing this issue

**Comment by selfissued** [comment]
Fixed by #44
