### ISSUE TITLE
Rename title of section 8.3 to "Resolve Entity"

### ISSUE THREAD

**Issue by Razumain** [openid/federation#40]
This is just a nit, but I'm throwing it in here for it to be noted and potentially fixed

The heading of 8.3 is currently "Resolve Entity Statement", but that is incorrect. As described by the leading text, you are not resolving an Entity Statement, but processed metadata and validated Trust Marks for the specified Entity.

**Comment by rohe** [comment]
You're right and it should be fixed.

**Comment by jcmelati** [comment]
If I understand the intention of the text, the `resolved metadata and (validated) Trust Marks for an Entity` are the result of the resolution of the subject's Entity Configuration Statement. The `resolve` endpoint exists solely to delegate the resolution of the trust chain to another party, as noted in [section 8.3.3](https://openid.net/specs/openid-federation-1_0.html#section-8.3.3).

In this case, the title should indeed be corrected, but I believe that "Resolve Entity Configuration Statement" clarifies exactly what is being resolved and makes it clear that Subordinate Statements cannot be resolved via the `resolve` endpoint.

**Comment by Razumain** [comment]
The fact remains that the resolver is neither returning an Entity Configuration, nor an Entity Statement. The resolve response has its own structure and mime type. I believe a title must reflect what is returned to the requester, not what data that is internally examined in the resolver.

**Comment by selfissued** [comment]
I agree with @Razumain and will create a PR.  @jcmelati, a Subordinate Statement is not an Entity, so I'm not worried about people confusing the two.
