### ISSUE TITLE
Inconsistent example regarding OP metadata claim request_authentication_signing_alg_values_supported 

### ISSUE THREAD

**Issue by cicnavi** [openid/federation#49]
In the description of the OP metadata claim 'request_authentication_signing_alg_values_supported' it is stated that if 'request_object' is one of the 'request_authentication_methods_supported', claim 'request_authentication_signing_alg_values_supported' must be present. However, in the example there is no 'request_authentication_signing_alg_values_supported', while 'request_object' is in 'request_authentication_methods_supported'. 

![image](https://github.com/user-attachments/assets/f7df1a2a-b1e1-4edb-85db-d2d4679d6577)

**Comment by selfissued** [comment]
Thanks Marko.  You're right.  We need to fix this!
