### ISSUE TITLE
Entities identifiers may contain query parameter or fragment components?

### ISSUE THREAD

**Issue by jogu** [openid/federation#54]
In https://openid.net/specs/openid-federation-1_0.html#section-1.2 for entity id it says "It MAY NOT contain query parameter or fragment components."

As per https://github.com/openid/federation/pull/27 I believe it was intended to forbid query/fragment components, so 'MAY NOT' should be a 'MUST NOT'.

**Comment by selfissued** [comment]
Yes, I'll correct.
