### ISSUE TITLE
Ambiguity of authority_hints Description

### ISSUE THREAD

**Issue by PedramHD** [openid/federation#58]
According to Section 3 of Draft 38, the `authority_hints` represent "the Entity Identifiers of Intermediate Entities or Trust Anchors that MAY issue Subordinate Statements about the Entity."

This statement is ambiguous: Are these just a hint that other Entities can use to create Trust Chains? Or are Entities not in the `authority_hints` not allowed to create Subordinate Statements about the Entity? In this case, the Trust Chain validation needs to take the `authority_hints` into account.

**Comment by Razumain** [comment]
Section 10 will not work unless `authority_hints` is present in all Entity Statements and that process repeats until no `authority_hints` are found, assuming that we have reached a Trust Anchor.

This seems to harmonise better with a requirement to include `authority_hints` in all statements except for statements issued by a Trust Anchor.

**Comment by peppelinux** [comment]
authority_hints MUST be present in Entity Configuration

authority_hints MUST NOT be present in Subordinate Statements

Both Entity Configuration and Subordinate Statements inherits the Entity Statement Class :-) but they extends it implementing different requirements

**Comment by PedramHD** [comment]
@Razumain The procedure described in Section 10.1 is not required when processing Trust Chains. For example, when processing an automatic client registration request, the OP could just use the chain contained in the request (Section 12.1.1.1.2):

> The OP MAY evaluate the statements in the trust_chain to make its Federation Entity Discovery procedure more efficient, especially if the RP contains multiple authority hints in its Entity Configuration.

and

> Whenever the OP uses a Trust Chain submitted by an RP, the OP MUST fully verify it, including every Entity Statement contained in it. A Trust Chain may be relied upon by the OP because it has validated all of its statements. This is true whether these statements are retrieved from their URLs or whether they are provided via the trust_chain request parameter in the Request Object.

But the validation procedure in Section 10.2 does not require any checks regarding the `authority_hints`, so the OP might accept a Trust Chain where the second Trust Chain Statement was created by an issuer not in the `authority_hints` of the Entity Configuration of the Chain subject.

**Comment by Razumain** [comment]
@PedramHD Agreed.
Authority ints are not required to validate a chain. That was not my point.

My point is that path construction, if you start with an EntityConfiguration, requires authority_hint to work. See section 10.1

> The next step is to iterate through the list of Intermediates listed in authority_hints, ignoring the authority hints that end in an unknown Trust Anchor, requesting an Entity Configuration from each of the Intermediates. If the received Entity Configuration contains an authority hint, this process is repeated.

I also agree with your original observation that it should be clear if checking authority hint is required for successful chain validation. I think it should be mandatory, and that it must match. Simply because that promotes interoperability for both validation and path construction.
