### ISSUE TITLE
Add a note to section 10 that allows the use of a resolve endpoint

### ISSUE THREAD

**Issue by Razumain** [openid/federation#66]
Section 12 refers to section 10 for the process to resolve peer entity data, but section 10 say nothing about the option to use a resolve endpoint for that purpose.

There are nothing wrong with section 10, except that it should say something like:

- There are two options to receive validated data about the peer
  - Use a resolve endpoint, or
  - Build and validate trust paths as described in this section
 
For parties that choose to use a resolve endpoint, none of the steps in section 10 are necessary, and I think it would benefit the standard to say so.

**Comment by peppelinux** [comment]
I can do this in a form of hints for informational purpose about the federation, keeping in mind that resolve is optional while fetch

**Comment by Razumain** [comment]
That is all I'm asking for. We agree that resolve is optional and may not be available. But if it is available, it should be treated as an equal alternative.
