### ISSUE TITLE
Trust Chain Selection During Registration Request Processing

### ISSUE THREAD

**Issue by SECtim** [openid/federation#85]
[Section 12.2.2.1](https://openid.net/specs/openid-federation-1_0-38.html#section-12.2.2.1) describes how an OP processes an RP's explicit client registration request.

### Scenario to illustrate the problem
For the purpose of a simpler explanation, let's assume that RP sent an Entity Configuration (instead of a Trust Chain).

Now, in step 2, OP collects and validates several Trust Chains from RP to several TAs.
Say, `chain1 = [RP, Im1, TA1]`, `chain2 = [RP, Im2, Im3, TA2]`, and `chain3 = [RP, Im4, TA2]` (all are valid).

> If the OP finds more than one acceptable Trust Chain, it MUST choose one Trust Anchor from those chains as the one to proceed with.

Hence, OP selects `TA2` to proceed with.

### Trust Chain in step 6

Step 6 in Section 12.2.2.1 says:

> The OP MUST assign an expiration time to the created registration. This time MUST NOT exceed the expiration time of the Trust Chain that the OP selected to process the request.

Which Trust Chain? OP never selected one, it just selected a Trust Anchor.

This can of course be fixed by requiring OP to select a Trust Chain instead of a Trust Anchor in step 2 (and adapting the text around `trust_anchor_id` in step 7 accordingly).

### Trust Chain in step 7

The 2nd paragraph of step 7 says:

> [...] The `authority_hints` claim MUST be set to the OP's Immediate Superior in the selected Trust Chain.

Which Trust Chain? Even assuming that OP selects a Trust Chain (instead of just a Trust Anchor) in step 2, this is still unclear - OP (or OP's immediate superior) may or may not be part of the chain selected in step 2 (say, OP selected `chain3` - it does not contain OP).
I.e., the set of possible Trust Chains from OP to the selected Trust Anchor `TA2` is (can be) disjoined from the set of possible Trust Chains from RP to `TA2`, and Section 12.2.2.1 does not seem to mention that OP has to collect, validate, and select one of them.

**Comment by selfissued** [comment]
This seems related to #7

**Comment by SECtim** [comment]
> This is the Trust Chain that the OP has for the RP. I.e. Trust Anchor --> RP.

There might be multiple Trust Chains, and the spec explicitly says so (now Step 3 in Section 12.2.2, the structure of 12.2 seems to have changed since the creation of this issue):
> If the request contains an Entity Configuration the OP MUST use it to complete the Federation Entity Discovery by collecting and evaluating the Trust Chains that start with the authority_hints in the Entity Configuration of the RP. After validating at least one Trust Chain, the OP MUST verify the signature of the received Entity Configuration. If the OP finds more than one acceptable Trust Chain, it MUST choose one Trust Anchor from those chains as the one to proceed with.

Selecting a Trust Anchor does not entail selection of a single Trust Chain as there might be multiple Trust Chains from a given TA to a given RP (e.g., a direct one and one with an Intermediate).

**Comment by selfissued** [comment]
There potentially being multiple paths between entities is being addressed in #150 .

**Comment by selfissued** [comment]
#85 addresses the Step 6 issue.  I'm still researching the Step 7 issue.

**Comment by selfissued** [comment]
The Step 7 issue was addressed in https://github.com/openid/federation/pull/157/commits/eec4e00cbee9ae55716aed3473002fb3fbd697e6 by making the `authority_hints` value in the Explicit Registration response refer to the RP's Immediate Superior in the Trust Chain chosen for it by the OP.
