### ISSUE TITLE
Obsolete wording on Federation Fetch Response

### ISSUE THREAD

**Issue by MichaelFraser1999** [openid/federation#92]
Section 8.1.2 contains the following text

> If the sub parameter references the same Entity as the iss parameter, returning the invalid_request error code is RECOMMENDED. See more about error responses in [Section 8.9](https://openid.net/specs/openid-federation-1_0.html#error_response).

With version 39 we removed the `iss` parameter from the fetch endpoint rendering this text out of date

**Comment by MichaelFraser1999** [comment]
Raised https://github.com/openid/federation/pull/93 as a proposed adjustment

**Comment by selfissued** [comment]
Thanks for the bug report and the fix!

**Comment by selfissued** [comment]
Fixed by #93
